spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.c7vhxyzo5nle.ap-northeast-2.rds.amazonaws.com:3306/my_database?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin
    password: choi0344

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate:
        default_batch_fetch_size: 1000
    database-platform: org.hibernate.dialect.MySQL8Dialect


  logging:
    level:
      org.hibernate.SQL: debug
# datasource:
# url: jdbc:h2:mem:testdb
# username: sa
# password:
# driver-class-name: org.h2.Driver
# jpa:
# hibernate:
# ddl-auto: create
# properties:
# hibernate:
# show_sql: true
# format_sql: true
# open-in-view: false
#logging.level:
#  org.hibernate.SQL: debug
# org.hibernate.type: trace